# Generated by Django 4.2.3 on 2023-11-25 09:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockItem',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('detail', models.CharField(default=None, max_length=255, null=True)),
                ('jm_id', models.CharField(default=None, max_length=255, null=True)),
                ('be_id', models.CharField(default=None, max_length=255, null=True)),
                ('unit_price', models.FloatField(default=None, null=True)),
                ('barcode_id', models.CharField(default=None, max_length=255, null=True)),
                ('piece', models.IntegerField(default=0, null=True)),
                ('discounted', models.BooleanField(default=False)),
                ('qt', models.FloatField(default=0.0, null=True)),
                ('cost', models.FloatField(default=0.0, null=True)),
                ('code', models.CharField(default=None, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('instance_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, null=True)),
                ('verified', models.BooleanField(default=False)),
                ('status', models.TextField()),
                ('email', models.EmailField(blank=True, default=None, max_length=254, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('state', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('zip', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.JSONField(default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.CharField(blank=True, max_length=30)),
                ('paid', models.CharField(blank=True, max_length=30)),
                ('totalTax', models.DecimalField(decimal_places=2, max_digits=65)),
                ('totalDiscounted', models.DecimalField(decimal_places=2, max_digits=65)),
                ('totalPrice', models.DecimalField(decimal_places=2, max_digits=65)),
                ('invoiceNumber', models.TextField()),
                ('credit', models.DecimalField(decimal_places=2, max_digits=65)),
                ('totalProfit', models.DecimalField(decimal_places=2, max_digits=65)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('require_date', models.DateTimeField(default=None, null=True)),
                ('customer', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='storesystem.userinfo')),
                ('items', models.ManyToManyField(to='storesystem.stockitem')),
            ],
        ),
    ]
