# Generated by Django 4.2.3 on 2023-11-25 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storesystem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockitem',
            name='taxactive',
            field=models.BooleanField(default=False),
        ),
    ]
