# Generated by Django 4.2.3 on 2024-03-31 16:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('storesystem', '0002_stockitem_taxactive'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='items',
        ),
        migrations.AddField(
            model_name='invoice',
            name='status',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='InvoiceItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255)),
                ('qty', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=65)),
                ('tax', models.DecimalField(decimal_places=2, max_digits=65)),
                ('inv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storesystem.invoice')),
            ],
        ),
    ]
